# Generated by Django 6.0.5 on 2026-06-07 09:33

from django.db import migrations
from django.conf import settings

# def set_site(apps, schema_editor):
#     Site = apps.get_model('sites', 'Site')

#     # site, created = Site.objects.get_or_create(pk=1)

#     # site.domain = settings.SITE_DOMAIN
#     # site.name = settings.SITE_NAME
#     # site.save()

#     site, created = Site.objects.get_or_create(
#     domain=settings.SITE_DOMAIN,
#     defaults={"name": settings.SITE_NAME}
#     )
#     #Version plus pro concernant la requete get database

def forwards(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site, created = Site.objects.get_or_create(pk=1)
    site.domain = settings.SITE_DOMAIN
    site.name = settings.SITE_NAME
    site.save()


def backwards(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site = Site.objects.get(pk=1)
    site.domain = "example.com"
    site.name = "example.com"
    site.save()



class Migration(migrations.Migration):

    dependencies = [
    ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
    migrations.RunPython(forwards, backwards),
    ]
